import {
  addImports,
  addPlugin,
  addRouteMiddleware,
  addServerPlugin,
  addTypeTemplate,
  createResolver,
  defineNuxtModule,
  useLogger,
} from '@nuxt/kit';
import { defu } from 'defu';
import type { DeepRequired } from 'ts-essentials';
import type { NuxtModule } from 'nuxt/schema';
import type {
  ModuleOptions,
  ModuleOptionsNormalized,
  ProviderAuthjs,
} from './runtime/shared/types';

const topLevelDefaults = {
  isEnabled: true,
  baseURL: '/api/auth',
  disableInternalRouting: false as boolean,
  disableServerSideAuth: false,
  originEnvKey: 'AUTH_ORIGIN',
  sessionRefresh: {
    enablePeriodically: false,
    enableOnWindowFocus: true,
  },
} satisfies ModuleOptions;

const authjsDefaults: DeepRequired<ProviderAuthjs> = {
  type: 'authjs',
  trustHost: false,
  defaultProvider: '',
  addDefaultCallbackUrl: true,
};

const PACKAGE_NAME = 'zitadel-auth';

/**
 * Nuxt module that wires Auth.js into the Nuxt runtime, registering
 * server handlers, the `useAuth` composable, route middleware, and
 * type augmentations.
 *
 * @public
 */
export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: PACKAGE_NAME,
    configKey: 'auth',
    compatibility: {
      nuxt: '>=4.0.0',
    },
  },
  setup(userOptions, nuxt) {
    const logger = useLogger(PACKAGE_NAME);

    const options = defu(
      {
        // We use `as` to infer backend types correctly for runtime-usage (everything is set, although for user everything was optional)
        provider: defu(
          userOptions.provider,
          authjsDefaults,
        ) as DeepRequired<ProviderAuthjs>,
      },
      userOptions,
      topLevelDefaults,
    );

    if (!options.isEnabled) {
      logger.info(`Skipping ${PACKAGE_NAME} setup, as module is disabled`);
      return;
    }

    nuxt.options.runtimeConfig = nuxt.options.runtimeConfig || { public: {} };
    nuxt.options.runtimeConfig.public.auth = options;

    const { resolve } = createResolver(import.meta.url);

    addImports([
      {
        name: 'useAuth',
        from: resolve('./runtime/app/composables/useAuth'),
      },
      {
        name: 'signInUrl',
        from: resolve('./runtime/shared/urls'),
      },
      {
        name: 'signOutUrl',
        from: resolve('./runtime/shared/urls'),
      },
    ]);

    nuxt.hook(
      // @ts-expect-error nitro:config hook exists but type definition is missing
      'nitro:config',
      (nitroConfig: {
        alias?: Record<string, string>;
        externals?: { inline?: string[] };
      }) => {
        nitroConfig.alias = nitroConfig.alias || {};

        nitroConfig.externals = defu(
          typeof nitroConfig.externals === 'object'
            ? nitroConfig.externals
            : {},
          {
            // Inline the SDK's runtime so Nitro bundles it into the
            // production output instead of attempting to externalize it
            // (which breaks when the SDK is linked via `file:../` because
            // Nitro emits a relative path from the chunk to the symlinked
            // location and miscounts the directory levels).
            //
            // Also inline @auth/core and its sub-paths: they are reached
            // via the SDK's runtime imports and would otherwise be
            // externalized into `.output/server/node_modules/@auth/core/`,
            // which doesn't exist when the SDK is symlinked.
            inline: [resolve('./runtime'), '@auth/core'],
          },
        );
        nitroConfig.alias['#auth'] = resolve('./runtime/server/services');
      },
    );

    addTypeTemplate({
      filename: 'types/auth.d.ts',
      getContents: () =>
        [
          '// AUTO-GENERATED BY @zitadel/nuxt-auth',
          "declare module '#auth' {",
          `  const { NuxtAuth }: typeof import('${resolve('./runtime/server/services')}')`,
          '}',
          '',
        ].join('\n'),
    });

    addTypeTemplate({
      filename: 'types/auth-misc.d.ts',
      getContents: () =>
        [
          '// AUTO-GENERATED BY @zitadel/nuxt-auth',
          `import { RouteOptions, AuthMeta } from '${resolve('./runtime/shared/types.ts')}'`,
          "declare module 'nitropack' {",
          '  interface NitroRouteRules {',
          '    auth?: RouteOptions',
          '  }',
          '  interface NitroRouteConfig {',
          '    auth?: RouteOptions',
          '  }',
          '}',
          "declare module '#app' {",
          '  interface PageMeta {',
          '    auth?: AuthMeta',
          '  }',
          '}',
          "declare module 'vue-router' {",
          '  interface RouteMeta {',
          '    auth?: AuthMeta',
          '  }',
          '}',
          '',
        ].join('\n'),
    });

    addRouteMiddleware({
      name: PACKAGE_NAME,
      path: resolve('./runtime/app/middleware/auth'),
      global: true,
    });

    addPlugin(resolve('./runtime/app/plugins/auth'));
    addPlugin(resolve('./runtime/app/plugins/session-refresh'));

    addServerPlugin(resolve('./runtime/server/plugins/assertOrigin'));
  },
}) satisfies NuxtModule<ModuleOptions>;

export type {
  GlobalMiddlewareOptions,
  ModuleOptions,
  ModuleOptionsNormalized,
  ProviderAuthjs,
  SessionRefreshConfig,
} from './runtime/shared/types';

export { AuthError, CredentialsSignin } from '@auth/core/errors';
declare module '@nuxt/schema' {
  // noinspection JSUnusedGlobalSymbols
  interface PublicRuntimeConfig {
    auth: ModuleOptionsNormalized;
  }
}
